### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by JeremyMarshall** [angular-fullstack/generator-angular-fullstack#1531]
I was wondering what the policy towards docker is.

There is a heroku deployer (which I use) but recently I've beed using Docker and now https://www.tutum.co/ from the dist folder. The problem as I see it is that the standard docker Node container needs a great deal of interaction when doing an `npm install` so the whole create and destroy is a bit slow. I put together a similar container which does the `npm install` ahead of time https://hub.docker.com/r/jeremymarshall/angular-fullstack-dist/

There is also a wider question of providing a mongo container and possibly using nginx as a reverse proxy ahead in a compose/tutum set

**Comment by adambarthelson** [comment]
When I use Docker with my Angular Fullstack applications, I've been using this: https://gist.github.com/adambarthelson/ef57b7b90814c771be9a02381ef2182b

This way it's compatible with Dockerhub's automated builds, and you're not having to manually push fresh images to Dockerhub like a savage.

An example ```docker-compose.yml``` that links this with a Mongo container is:

```
version: '2'

services:
  web:
    image: you/your-angular-fullstack-image
    links:
      - mongodb:mongodb
    ports:
      - '8080:8080'
    restart: always
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
```
