### ISSUE TITLE
Add option to test phase to generate junit output

### ISSUE THREAD

**Issue by JeremyMarshall** [angular-fullstack/generator-angular-fullstack#2066]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.0
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Gulp
Client Tests |  Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

It would be good to have a feature where the test phase can generate optional junit XML files
e.g.
`gulp test:junit`
This would make the tests for the generator itself more visible to circleci https://circleci.com/docs/test-metadata/ which I think is the CI for v4.0.0
This would also help users of the generator as junit is a standard in Jenkins, Bamboo and TeamCity

I think the tricky part will be assembling the tests from all the temporary apps which are part of the testing

I looked into this as I need the tests to pass so circleci can go ahead and create a branch for the docker image https://github.com/angular-fullstack/generator-angular-fullstack/issues/1959

such as in circle.yml
```yml
## Deployments
deployment:
  docker:
    # update the upstream dockerfile after a push
    branch: [master, docker-integration]
    commands:
      - generator-angular-fullstack/angular-fullstack-dockerfile/create_branch.sh

```
