### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by azachar** [angular-fullstack/generator-angular-fullstack#2067]
Hi there!

First of all, thank you for your amazing job! 

Do you plan to provide some examples of continuous integration to for example circleci, codeship or any other?  

I guess this could be managed by the CI providers directly.

Thank you for your answer.

Best regards,
Andrej

**Comment by ronrbc** [comment]
i'm also following on this. very much interested in hearing anything for the experts: do you use ci? what is your preferred way of pushing your work to prod? manual? automatic?  where do you host? what's your db solution?  thanks!

**Comment by Awk34** [comment]
As of right now, we include a `travis.yml` in the generated project files. It would be great to have the option to include various CI configs. I like Circle CI (the generator uses it), but I've also used Codeship, which I don't think supports a config file.

**Comment by azachar** [comment]
I like https://circleci.com/, but for some reason, you are unable to associate more than one Heroku account with it.. Very said!

Here is my circle.yml  (for a project generated above a year ago, so perhaps it can still work with the current code base). 

```
dependencies:
  cache_directories:
    - 'client/bower_components'

  post:
    - gem install sass
    - npm install grunt-cli
    - bower install

deployment:
  development:
     branch: /fea-.*/
     commands:
         - grunt build
         - heroku maintenance:on --app your-heroku-app-name
         - grunt buildcontrol:circle
         - heroku maintenance:off --app your-heroku-app-name
```
in the ``Grunfile.js`` file in the section build control I had add the following config:

```
buildcontrol: 
...
 circle: {
        options: {
          remote: 'git@heroku.com:your-heroku-repo.git',
          branch: 'master'
        }
      },
```

As far as I know there is no file config for Codeship.

Cheers,
Andrej

**Comment by Awk34** [comment]
@azachar you shouldn't need the Ruby Sass gem anymore. Also, my Circle config contains this:

```yaml
machine:
  node:
    version: 5.11.1
  post:
- npm install -g gulp-cli
```
